plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true

exclude:
  - README.md

include:
  - "*.md"

remote_theme: pages-themes/midnight@v0.2.0

repo: "container_aria"