version: "3.9"
services:
  node1:
    build:
      context: ./node
    container_name: node1
    hostname: node1
    networks:
      - ansible_net
    tty: true
    stdin_open: true

  node2:
    build:
      context: ./node
    container_name: node2
    hostname: node2
    networks:
      - ansible_net
    tty: true
    stdin_open: true
  
  node3:
    build:
      context: ./node
    container_name: node3
    hostname: node3
    networks:
      - ansible_net
    tty: true
    stdin_open: true

  ansible:
    build:
      context: ./controller
    container_name: ansible
    hostname: ansible
    networks:
      - ansible_net
    volumes:
      - /mnt/c/Users/ariaf/OneDrive/Dokumen/github_aria/container_aria/ansible/:/ansible_aria:Z
    tty: true
    stdin_open: true
    depends_on:
      - node1
      - node2

networks:
  ansible_net:
    driver: bridge

